apiVersion: v1
kind: Pod
metadata:
  name: hybridconnector
  labels:
    app: web
spec:
  containers:
    - name: client-connector
      image: anthostest2.azurecr.io/hybridclientconnector:v2
  imagePullSecrets:
    - name: tryanthostest2
