apiVersion: v1
kind: Pod
metadata:
  name: hybridclientconnector
  labels:
    app: web
spec:
  containers:
    - name: client-connector
      image: anthostest2.azurecr.io/hybridconnector:v2
  imagePullSecrets:
    - name: tryanthostest2
